apiVersion: v2
name: brim-services
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: recruiter
    version: 0.1.0
    repository: file://../recruiter
  - name: common
    version: 0.1.0
    repository: file://../common
