# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

# Go Docker environment
executors:
  go_builder:
    docker:
      - image: circleci/golang:1.13-buster-node

commands:
  log_date:
    description: Log date
    steps:
      - run:
          name: Log date
          command: date -u

jobs:
  build:
    executor: go_builder
    steps:
      - log_date
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
            - npm-deps-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Go vet
          command: 'make vet'
      - run:
          name: Go fmt
          command: 'make fmt'
      - run:
          name: Unit Tests
          command: 'make test-unit'
      - run:
          name: Build
          command: 'make build'
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - save_cache:
          key: npm-deps-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  system_test:
    docker:
      - image: circleci/golang:1.13-buster
    steps:
      - log_date
      - attach_workspace:
          at: .
      - run:
          name: System Tests
          command: 'make test-system'

workflows:
  version: 2
  main:
    jobs:
      - build
      - system_test:
          requires:
            - build
