apiVersion: v2
name: postgres
description: A Helm chart for postgres
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
    condition: postgresql.clusterInstance.enabled
