postgresql:
  clusterInstance:
    enabled: true
    
  # Possible values: standalone, replication.
  architecture: standalone
  
  # Username, password, database for zqd cluster use.
  postgresqlUsername: "zqd"
  postgresqlDatabase: "zqd"
  existingSecret: "postgres"
  
  image:
    tag: "11"
  
  # Enable persistence using Persistence Volume Claims.
  persistence:
    enabled: true
  
    accessModes:
      - ReadWriteOnce
  
    size: 8Gi

