recruiter:
  replicaCount: 1
root:
  datauri: "file:///spaces"
  recruiterAddr: z-recruiter:9867
worker:
  recruiterAddr: z-recruiter:9867

global:
  AWSRegion: ""
  image:
    repository: "localhost:5000/"
    pullPolicy: Always
    tag: "zqd"
  imagePullSecrets: []
  useCredSecret: false
