name: "Tests"

on:
  pull_request:
  push:
    branches:
      - master
      - zng-output-check

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v1
      - run: go mod download
      - run: make fmt
      - run: make tidy
      - run: make vet
      - run: make test-generate
      - run: make test-unit
      - run: make test-system
      - run: make test-zeek
      - run: make test-heavy
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v1
      - run: go test -short ./...
      - run: mkdir dist -ea 0
      - run: go build -o dist ./cmd/...
      - run: go test -v -tags=system ./tests
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  zng-output-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make zng-output-check
