name: "Tests"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - uses: actions/checkout@v1
      - run: go mod download
      - run: make fmt
      - run: make tidy
      - run: make vet
      - run: make test-unit
      - run: make test-system
      - run: make test-heavy
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - uses: actions/checkout@v1
      - run: go test -short ./...
      - run: mkdir dist -ea 0
      - run: go build -o dist ./cmd/...
      - run: go test -v -tags=system ./tests
