name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: go mod download
      - run: make fmt
      - run: make tidy
      - run: make vet
      - run: make test-generate
      - run: make test-unit
      - run: make test-system
      - run: make test-heavy
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: go mod download
      - run: make test-unit
      - run: make test-system
      - run: make test-heavy
  z-output-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - run: make install
      - run: make z-output-check
