name: EKS Test 1

on: 
  push:
    branches:
      - eks-test-1
  workflow_dispatch:
    inputs:
      numWorkers:
        description: 'Number of Workers'     
        required: true
        default: '4'

jobs:
  eks-test-zapi-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - env:
          NAMESPACE: ci-${{ github.ref }}
        run: |
          echo GITHUB_RUN_ID is $GITHUB_RUN_ID
          make install
          aws eks --region us-east-2 update-kubeconfig --name zq-test
          kubectl config set-context --current --namespace=$NAMESPACE
          kubectl port-forward svc/recruiter-zqd 8020:9867 &
          kubectl port-forward svc/root-zqd 9867:9867 &
          sleep 2 # wait for port-forwards to complete
          curl http://localhost:8020/recruiter/listfree        
          zapi ls 
          # echo "Number of Workers: ${{ github.event.inputs.numWorkers }}"
      - run: |
         time zapi -id sp_1lQzT9N8bRG3aW6kcLDPUbdEJH3 get -workers 1 -t '"FgzbkQ15TOoOENn1lb" | sort tx_hosts'
         time zapi -id sp_1lQzT9N8bRG3aW6kcLDPUbdEJH3 get -workers 2 -t '"FgzbkQ15TOoOENn1lb" | sort tx_hosts'
         time zapi -id sp_1lQzT9N8bRG3aW6kcLDPUbdEJH3 get -workers 4 -t '"FgzbkQ15TOoOENn1lb" | sort tx_hosts'
