name: Perf compare

on:
  push:
    branches:
      - rc-v*
  schedule:
    - cron: '5 8 * * *'
  workflow_dispatch:

jobs:
  perf-compare:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Add zeek-cut to PATH
      run: |
        echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
        curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
        sudo apt update
        sudo apt -y install zeek
        echo /opt/zeek/bin >> $GITHUB_PATH
    - run: PATH="$PWD/dist:$PATH" make perf-compare
