name: release assets
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: go mod download
    - run: make fmt
    - run: make tidy
    - run: |
          sudo apt-get update
          sudo apt-get install -y zip libnet1 libjansson4
    - run: make vet
    - run: make test-generate
    - run: make test-unit
    - run: make test-system
    - run: make test-heavy
    - uses: goreleaser/goreleaser-action@v2
      with:
        args: release --rm-dist -f scripts/goreleaser.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
